aws-samples/dbt-glue

README.md
dbt/adapters/glue/connections.py
dbt/adapters/glue/gluedbapi/connection.py
dbt/adapters/glue/gluedbapi/cursor.py
dbt/adapters/glue/impl.py
dbt/include/glue/macros/adapters.sql
dbt/include/glue/macros/materializations/incremental/incremental.sql
dev-requirements.txt
setup.py

Fix doc and debug

---

README.md
dbt/adapters/glue/credentials.py
dbt/adapters/glue/gluedbapi/commons.py
dbt/adapters/glue/gluedbapi/connection.py
dbt/adapters/glue/gluedbapi/cursor.py
dbt/adapters/glue/impl.py
setup.py

add query timeout parameter

---

README.md
dbt/adapters/glue/credentials.py
dbt/adapters/glue/gluedbapi/commons.py
dbt/adapters/glue/gluedbapi/connection.py
dbt/adapters/glue/gluedbapi/cursor.py
setup.py

add query timeout

---

CHANGELOG.md
dbt/adapters/glue/credentials.py
dbt/adapters/glue/gluedbapi/connection.py
dbt/adapters/glue/impl.py
dbt/include/glue/macros/materializations/incremental/incremental.sql

resolves issues while passing glue connections to dbt
Modified Connection argument for Glue Session.
Boto3 Glue [create_session](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.create_session) function accepts connection info as Dictionary, where are the existing code of glue sends info string.
**DBT Profile:**
```yaml
aws_demo_proj:
target: aws_dev
outputs:
aws_dev:
type: glue
query-comment: This is a glue dbt example
role_arn: arn:aws:iam::xxxxxxxxx:role/dbt-demo-role
region: eu-central-1
workers: 5
worker_type: G.2X
schema: "det"
database: "det_landing_data_platform"
session_provisioning_timeout_in_seconds: 120
location: "s3://det-landing-data-lake"
connections: 'delta_lake'
```
**Existing Arguments for connections passed to  Glue Create …

Modified Connection argument for Glue Session and table relation information for incremental mode

---

README.md
dbt/adapters/glue/credentials.py
dbt/adapters/glue/gluedbapi/connection.py
dbt/adapters/glue/impl.py
dbt/include/glue/macros/adapters.sql
dbt/include/glue/macros/materializations/incremental/incremental.sql
dbt/include/glue/macros/materializations/snapshot.sql
setup.py
tests/conftest.py
tests/functional/adapter/test_basic.py
tests/single_functional/adapter/single_test.py

Delta lake integration

---

dbt/adapters/glue/impl.py
dbt/include/glue/macros/materializations/incremental/incremental.sql
setup.py

fix hudi partition

---

dbt/adapters/glue/impl.py

resolves #
**Description**
Enable multiple partitions for Delta Tables
**Checklist**

Enable Multiple Partitions for Delta Tables

---

CHANGELOG.md
README.md
dbt/adapters/glue/credentials.py
dbt/adapters/glue/gluedbapi/connection.py

resolves #102 
Added new default args to be able to send parameters to glue. Also I added the documentation to add monitoring to the glue interactive session

Monitoring and default_parameters 

---

README.md

resolves #109
<
Added documentation to enable Glue Auto Scaling

Adds how to enable auto scaling on documentation

---

CHANGELOG.md
README.md
dbt/adapters/glue/impl.py
dbt/include/glue/macros/materializations/incremental/incremental.sql
dbt/include/glue/macros/materializations/snapshot.sql

resolves #62 
- add ability to override any hudi option

add ability to override any hudi options

---

CHANGELOG.md
README.md
dbt/adapters/glue/impl.py

resolves #135
related to #134
Update the readme to point the difference in configuration between users that go with Athena version 3 or Athena version 2

update readme with configuration for icerberg v0.14.0 

---

CHANGELOG.md
dbt/adapters/glue/impl.py

resolves #146
The PR will fix the Exception handling for the dbt-glue that at the moment proxy the dbt exception and make the DBT wrongly report as PASS.

Raise DBT exception from dbt-glue failure for correct DBT status report

---

CHANGELOG.md
dbt/adapters/glue/impl.py

resolves #144 
Fixes an issue with HUDI merge strategy.
I had previously closed #149 in favor of #162, however #162 then got closed in favor of #149.  Reopening PR.

Fixed HUDI merge strategy (reopened)

---

README.md

Update readme for details on how to add configuration to run DBT job on another AWS account

Add details for cross account in README.md

---

dbt/adapters/glue/gluedbapi/connection.py

resolves #
As discussed with @menuetb on slack [thread](https://getdbt.slack.com/archives/C02R4HSMBAT/p1688109277564799?thread_ts=1688066435.035069&cid=C02R4HSMBAT) - replacing the action of deleting the session with stopping the session to preserve metadata corresponding to the sessions

replace delete-session with the stop-session API

---

dbt/adapters/glue/impl.py

resolves #
recommended to remove extra validation overhead - https://hudi.apache.org/docs/configurations/#hoodieconsistencycheckenabled

remove s3 consistency check

---

dbt/adapters/glue/impl.py
dbt/include/glue/macros/materializations/incremental/incremental.sql

resolves #213
Calls "MSCK REPAIR" only when the table is partitioned

Fixed msck repair call for non-partitioned tables

---

dbt/adapters/glue/impl.py

resolves #219
Created an additional step to set AdditionalLocations in delta athena tables.
Only symlink tables are in scope. (i.e. delta_athena_prefix is not None)

Support delta tables in Athena managed by Lake Formation

---

dbt/adapters/glue/connections.py
dbt/adapters/glue/credentials.py
dbt/adapters/glue/gluedbapi/connection.py

Rebase for pr234

---

CHANGELOG.md
dbt/adapters/glue/__version__.py
dbt/adapters/glue/gluedbapi/connection.py

Fix reuse session

---

CHANGELOG.md
README.md
dbt/adapters/glue/__version__.py
dbt/adapters/glue/credentials.py
dbt/adapters/glue/impl.py

add glue optimistic lock option for iceberg tables

---

dbt/adapters/glue/gluedbapi/connection.py

This PR replaces retry logic with botocore's WaiterModel.
This also removes the issue that dbt-glue calls too many StopSession API even during session is in Provisioning/Stopping state.

Replace retry logic with WaiterModel

---

.github/workflows/integration.yml
.github/workflows/main.yml
dev-requirements.txt

Update dev-requirements to be compatible with dbt-core/dbt-spark 1.7.1

Update dev-requirements to be compatible with dbt-core/dbt-spark 1.7.1

---

dev-requirements.txt

Change requirements

---

tests/functional/adapter/test_basic.py

fix test generic

---

CHANGELOG.md
README.md
dbt/adapters/glue/__version__.py
setup.py

Upgrade to v172

---

.gitignore
CHANGELOG.md
dbt/adapters/glue/impl.py

resolves #58
Using the `get_paginator` to make a continuation call over all databases defined in the targeted glue catalog.

Pagination bug

---

CHANGELOG.md
README.md

- fixed README.md typo in pip flag
- remove git installation instruction in setting up a virtual environment section.

chore(docs): update typo in README.md

---

dbt/adapters/glue/impl.py
dbt/include/glue/macros/materializations/incremental/strategies.sql

resolves #
PR addressing the following issue with multiple partition key;
https://github.com/aws-samples/dbt-glue/issues/345
Handle multiple partition columns in the model configurations. Delta merge fails. 

updating partition column as whole string

---

CHANGELOG.md
dbt/adapters/glue/__version__.py
dbt/adapters/glue/connections.py
dbt/adapters/glue/credentials.py
dbt/adapters/glue/gluedbapi/commons.py
dbt/adapters/glue/gluedbapi/connection.py
dbt/adapters/glue/gluedbapi/cursor.py
dbt/adapters/glue/impl.py
dbt/adapters/glue/lakeformation.py
dbt/adapters/glue/relation.py
dbt/adapters/glue/util.py
dev-requirements.txt
setup.py
tests/unit/test_adapter.py

Containing followings
* https://github.com/aws-samples/dbt-glue/pull/387
* https://github.com/aws-samples/dbt-glue/pull/385
Upgrade dbt versions
* dbt-core 1.8.1
* dbt-spark 1.8.0
* dbt-tests-adapter 1.8.1

Upgrade dbt version

---

CHANGELOG.md
dbt/adapters/glue/gluedbapi/connection.py

resolves #395
Removed slash from request origin.

Removed slash in request origin

---

CHANGELOG.md

resolves #
- [] This PR includes tests, or tests are not required/relevant for this PR

Preparing for Release v1.8.6

---

CHANGELOG.md
dbt/adapters/glue/__version__.py
dev-requirements.txt
setup.py

This is to track the tasks for release v1.9.0.
* Include merging https://github.com/aws-samples/dbt-glue/pull/479 and https://github.com/aws-samples/dbt-glue/pull/480.

Preparing for Release v1.9.0

---

.github/workflows/integration.yml
.github/workflows/main.yml

This is continuation of https://github.com/aws-samples/dbt-glue/pull/508.

Upgrade upload/download artifacts v4

---

CHANGELOG.md
dbt/adapters/glue/__version__.py
dbt/adapters/glue/impl.py
dev-requirements.txt
setup.py

This is to track the tasks for release v1.9.2 including:
* https://github.com/aws-samples/dbt-glue/pull/515
* https://github.com/aws-samples/dbt-glue/pull/511
* https://github.com/aws-samples/dbt-glue/pull/510
* https://github.com/aws-samples/dbt-glue/pull/504
* https://github.com/aws-samples/dbt-glue/pull/502

Preparing for Release v1.9.2

---

CHANGELOG.md
dbt/include/glue/macros/adapters.sql
dbt/include/glue/macros/materializations/incremental/incremental.sql
dbt/include/glue/macros/materializations/incremental/strategies.sql
tests/functional/adapter/test_iceberg.py
tests/unit/macros/test_macros.py

This is for resolving the issue 1 reported in #486.

Fixed temporary view issue

---

CHANGELOG.md
dbt/adapters/glue/impl.py
dbt/include/glue/macros/adapters.sql
dbt/include/glue/macros/materializations/incremental/incremental.sql
dbt/include/glue/macros/materializations/incremental/strategies.sql
dbt/include/glue/macros/materializations/snapshot.sql
tests/functional/adapter/test_iceberg.py
tests/unit/macros/test_macros.py

This PR fixes missing catalog identifier related issues for Iceberg.

Fix missing catalog identifier related issues for Iceberg

---

CHANGELOG.md
dbt/include/glue/macros/iceberg_helper.sql

Reduce debug logging

---

CHANGELOG.md
dbt/include/glue/macros/materializations/incremental/incremental.sql
dbt/include/glue/macros/materializations/table.sql
tests/functional/adapter/test_iceberg.py

Fix invalid Spark relation type: iceberg_table

---

CHANGELOG.md
dbt/adapters/glue/__version__.py
dev-requirements.txt
setup.py

This is to track the tasks for release v1.9.4 including:
* https://github.com/aws-samples/dbt-glue/pull/542
* https://github.com/aws-samples/dbt-glue/pull/541
* https://github.com/aws-samples/dbt-glue/pull/528
* https://github.com/aws-samples/dbt-glue/pull/544
* https://github.com/aws-samples/dbt-glue/pull/540
* https://github.com/aws-samples/dbt-glue/pull/538

Preparing for v1.9.4
