aws-samples/dbt-glue

dbt/include/glue/macros/materializations/incremental/incremental.sql
When running an incremental model with glue and `incremental_strategy: insert_overwrite` glue deleted all partitions except the new/overwritten partitions.
**usage_example model**
```
{{ config(
materialized='incremental',
partition_by=['event_date'],
tags='example',
incremental_strategy='insert_overwrite'
) }}
SELECT
id,
event_date
FROM {{ ref('usg_usage_example') }} WHERE event_date = date '{{ var("start_date") }}'
```
`dbt run --select +usage_example --vars '{start_date: 2022-01-01}'`
**existing partitions:**
event_date=2022-01-01
`dbt run --select +usage_example --vars '{start_date: 2022-01-02}'`
**existing partitions:**
event_date=2022-01-02
**expected partitions:**
event_date=2022-01-01
event_date=2022-01-02
By submitting this pull request, I confirm that you can use, modify, copy, …
=> fixing wrong statement for setting partitionOverwriteMode to DYNAMIC

CHANGELOG.md, dbt/include/glue/macros/adapters.sql
Glue DB does not support a Type of TEXt which is the default STRING type in DBT due to it being based on the Postgres API.
This macro overrides that and sets it correctly to STRING which in turn allows use of dbt_expectations
=> Override type_string

CHANGELOG.md, dbt/adapters/glue/gluedbapi/cursor.py
resolves #87 
Added a function to add an end space in case of single quoute at the end of a query. Ex: WHERE column='foo'
=> Fixes errors when trying to execute queries that finishes with single quote 

CHANGELOG.md, README.md, dbt/adapters/glue/credentials.py, dbt/include/glue/macros/adapters.sql, dbt/include/glue/sample_profiles.yml
resolves #93 
Changes in credentials
=> Force database parameter must be omitted or have the same value as schema 

CHANGELOG.md, setup.py
resolves #85 
This updates setup.py to support a min and max dbt-core/dbt-spark version allowing us to support version. 1.2.0 and 1.3.0 for a period.
=> Allow DBT 1.3.0

CHANGELOG.md, dbt/include/glue/macros/materializations/incremental/incremental.sql, setup.py
resolves #99
dbt-core has a bug that doesn't consider the the full_refresh config in the `flags.FULL_REFRESH`. This PR introduce a small change that consider also the `full_refresh` config parameter.
To test this implementation, I used this this config
```
{{ config(
materialized='incremental',
file_format='parquet',
incremental_strategy='insert_overwrite',
partition_by=['report_date'],
full_refresh = True
) }}
```
having that lead the the incremental do to a full refresh, therefore the table is dropped and recreated.
Benefits of this are:
- a consistent behaviour with the usage of the `is_incremental()` macro, that kicks in when the `full_refresh` flag is set to True.
- when adding new columns, we want to run a full_refresh mode, hence changing minimal configuration. The  `full_refresh` …
=> Consider full_refresh config when using incremental model

CHANGELOG.md, README.md, dbt/adapters/glue/impl.py, dbt/include/glue/macros/adapters.sql, setup.py
When working with Iceberg I noticed that the final / in the location of the table create weird extra / slash in the prefix of the objects in S3.
When using custom location of this type 's3://my_bucket/db/table' the issue doesn't persist. 
Therefore I decided to use this default behaviour creating a `get_iceberg_location` to return default location without final /. 
The final slash makes my iceberg tables unreadable from trino, somehow athena seems dealing with it, as the glue/spark.
See this related issue https://github.com/apache/iceberg/issues/4582.
Using version older then 0.13 fix the issue partially, as the metadata objects still suffer of the same problem (this must be addressed to the community developing Iceberg, I will reach out), for now that is the best fix to be able to use …
=> Fix inconstant iceberg default location due to final trailing slash

dbt/include/glue/macros/adapters.sql
Adds a location to temp table definitions to resolve errors in 0.3.4
For example:
```
14:31:21    Glue cursor returned `error` for statement None for code SqlWrapper2.execute('''
...
14:31:21        DROP TABLE IF EXISTS example_db.example_table_tmp
14:31:21        dbt_next_query
14:31:21        create table example_db.example_table_tmp
14:31:21        as
14:31:21          
14:31:21    
14:31:21    select
...
14:31:21      '''), IllegalArgumentException: Can not create a Path from an empty string
```
This error seems to occur because the full specification should be:
```
create table example_db.example_table_tmp
location 's3://some-s3-path'
as 
select
...
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
=> Specify location for tmp table

CHANGELOG.md, README.md, dbt/adapters/glue/credentials.py, dbt/adapters/glue/impl.py
resolves #
In response to comments on previously merged PR (#130) this PR : 
- adds details on Iceberg documentation (provide details on commit locking, catalog alias. provide least privilege IAM permissions for DynamoDB Commit Locking. Correct typos)
- adds customizable DynamoDB table name for Iceberg Commit Locking.
- performs refactoring of unused --conf parameter for Iceberg file format (warehouse_path)
=> Adding iceberg support

dbt/adapters/glue/impl.py
This is useful to register python UDFs in the underlying pyspark to be used elsewhere in the sql models! These macros can be attached to the dbt lifecycle hooks - https://docs.getdbt.com/docs/build/hooks-operations#getting-started-with-hooks-and-operations
Example registration of UDF (hex to integer conversion): 
```
{% macro register_udf_hex_to_int() %}
{% if execute %}
{% set code = """
from pyspark.sql.functions import udf
from pyspark.sql.types import IntegerType
@udf(IntegerType())
def hex_to_int(x):
return int(x, 16)
spark.udf.register('hex_to_int', hex_to_int)
""" %}
{% do adapter.execute_pyspark(code) %}
{% endif %}
{% endmacro %}
```
=> add execute_pyspark capability for registering python/pyspark UDFs

dbt/include/glue/macros/materializations/incremental/incremental.sql
resolves #
Resolves https://github.com/aws-samples/dbt-glue/issues/181
Move the step of running pre_hooks before creating temp table in incremental strategy.
=> run pre_hooks before create tmp table

dbt/adapters/glue/gluedbapi/connection.py
resolves #
```KeyError: 'credential_provider'```
Building boto3 client with DEFAULT session is breaking when using threads - [Reference used](https://github.com/boto/boto3/issues/1592#issuecomment-1379880226)
=> use session to build client - to be threadsafe

dbt/adapters/glue/impl.py, dbt/include/glue/macros/materializations/incremental/incremental.sql
resolves #
This will help to split the pyspark execution scripts using pre-hooks to prepare for any runtime variables to be read from datasources
Example usage:
```
{% macro set_max_hoodie_commit_time(schema, table_name) %}
{% if execute %}
{% set code = """
max_hoodie_commit_time_df = spark.sql('select max(_hoodie_commit_time) as max from " ~ schema ~ "." ~ table_name ~ "')
collect = max_hoodie_commit_time_df.collect()
max_hoodie_commit_time = collect[0]['max']   
""" %}
{% do adapter.execute_pyspark(code) %}
{% endif %}
{% endmacro %}
```
```
{{ 
config(
pre_hook="{{ set_max_hoodie_commit_time(this.schema, this.identifier) }}",
substitute_variables=["max_hoodie_commit_time"],
)
}}
select * from table
where _hoodie_commit_time >= '<SUBSTITUTE_VARIABLE_0>'
```
By submitting this pull …
=> enable models to substitute sql with pyspark variables

dbt/adapters/glue/gluedbapi/connection.py, setup.py
- fix requirement to use boto3 version for LakeFormation Tags
- Fix cancel statement on glue interactive sessions
resolves #203
=> fix the boto3 version to use lakeformation tags

dbt/adapters/glue/connections.py, dbt/adapters/glue/credentials.py, dbt/adapters/glue/gluedbapi/connection.py, dbt/adapters/glue/gluedbapi/cursor.py
resolves #200 #210
1. re-use the glue-session to run multiple dbt run commands, add two config options. 
|Option | Description | Mandatory|
-- | -- | --
|glue_session_id|set a glue session id you need to use|no|
|glue_session_reuse| If set to true, the glue session will not be closed for re-use. If set to false, the session will be closed|no|
2. glue session state do not have   RUNNING  and CLOSED ,but have STOPPED ,STOPPING,TIMEOUT. Fixed these sates.
=> re-use the glue-session to run multiple dbt run commands

dbt/adapters/glue/impl.py
Fixes bug mentioned in #220 
#220 introduced unwanted behavior in case the AdditionalLocations is not empty. 
=> Fixed AdditionalLocations append issue

.github/workflows/integration.yml, tox.ini
=> Integration test

tox.ini
resolves #240
currently, only bespoke unit tests are running, not the adapter integration tests provided by dbt Labs. This PR should fix that so that [`tests/functional/adapter/test_basic.py`](https://github.com/aws-samples/dbt-glue/blob/main/tests/functional/adapter/test_basic.py) will now run.
Note that there are MANY more tests provided that are still not set up to run (see [dbt-core's `tests/adapter/dbt/tests/adapter/` dir](https://github.com/dbt-labs/dbt-core/tree/e547c0ec6444b11c677c54506e09f903bcce29a0/tests/adapter/dbt/tests/adapter) for a more comprehensive list
=> ensure GHA's tox runs integration tests

CHANGELOG.md, README.md
In the past, users had to configure `extra_py_files` to run Delta Python API. However, now it's no longer required because AWS Glue resolved the limitation.
Existing integration tests already cover this. There's no such configuration in the configuration for the integration tests https://github.com/aws-samples/dbt-glue/blob/main/tests/conftest.py
=> [doc] Remove unnecessary extra_py_files for Delta Lake

README.md
`--conf spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog` is not shown in the readme. Just a formatting issue.
=> [minor][doc] Fix Iceberg config in README

tests/functional/adapter/test_basic.py
=> fix test generic

dbt/adapters/glue/connections.py, tests/functional/adapter/test_basic.py, tests/functional/adapter/test_docs.py, tests/functional/adapter/test_snapshot.py
This is the alternative PR of https://github.com/aws-samples/dbt-glue/pull/274 to avoid conflicts and enable all the basic tests.
=> all basic tests enabled

dbt/adapters/glue/connections.py
Revert the change in connections.py to fix test_snapshot failure 
```
tests/functional/adapter/test_snapshot.py::TestSnapshotCheckColsGlue::test_snapshot_check_cols FAILED                                                 [100%]
```
=> Revert the change in get_result_from_cursor to fix test

dbt/adapters/glue/credentials.py, dbt/adapters/glue/impl.py, dbt/include/glue/macros/adapters.sql
resolves #285 
The CreateDabase operation is performed with the caller role. We want it to be performed by the glue session role_arn provided in profiles.yml.
=> Fix wrong role create db#285

dbt/adapters/glue/credentials.py, dbt/adapters/glue/impl.py
In # 319, We needed to revert multiple PRs including #286.
This PR is to re-submit PR #286 to fix credential handling for use_interactive_session_role_for_api_calls.
The CreateDabase operation is performed with the caller role. We want it to be performed by the glue session role_arn provided in profiles.yml.
Important note: There is a difference from #286. This PR does not change default value for `use_interactive_session_role_for_api_calls parameter`.
=> Re-submit #286 to fix credential handling for use_interactive_session_role_for_api_calls

dbt/adapters/glue/column.py, dbt/adapters/glue/connections.py, dbt/adapters/glue/gluedbapi/cursor.py, dbt/adapters/glue/impl.py, dbt/include/glue/macros/adapters.sql
In # 319, We needed to revert multiple PRs including https://github.com/aws-samples/dbt-glue/pull/297.
This PR is to re-submit PR 297 to add minimal model contract enforcement for glue adapter.
This PR adds limited dbt model contract enforcement for the glue adapter. It adds a call to the `get_assert_columns_equivalent()` macro which is used to enforce the schemas for view and table materializations.
I say "limited" because it's missing a portion of the enforcements which includes but not limited to [constraints](https://docs.getdbt.com/reference/resource-properties/constraints) and potential various Glue specific datatypes. In this PR, I only addressed the `string` type.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
=>  Re-submit #297 to enable users to fix their glue_session_id name and re-use it

CHANGELOG.md, tests/unit/test_adapter.py
moto version is upgraded to 5.x via #334 but it broke unit tests. This PR is to fix the broken unit tests.
=> Fix unit test failure caused by moto 5 upgrade

CHANGELOG.md, dbt/adapters/glue/gluedbapi/connection.py
This PR addresses the issue related to sharing _create_session_config class attribute among Glue sessions. The fix prevents from overriding this attribute and enhances isolation.
Relates to https://github.com/aws-samples/dbt-glue/pull/234
=> Fix _create_session_config isolation

CHANGELOG.md, dbt/include/glue/macros/adapters.sql, tests/functional/adapter/test_basic.py
resolves #360 
This PR addresses the fix for a bug related to the usage of custom_location for tmp table creation for the default table format in incremental materialization. It was decided to use the location set up in the profile instead of writing to the same location where the original table resides. 
=> Fix tmp table location for the default file_format when custom_location is provided

CHANGELOG.md, dbt/adapters/glue/gluedbapi/connection.py
resolves #351
pass session_provisioning_timeout_in_seconds as timeout instead of delay in get_session_waiter()
=> Fix session provisioning timeout and delay handling

CHANGELOG.md, dbt/include/glue/macros/materializations/incremental/incremental.sql
resolves #330 
Adds a call to the macro [_process\_schema\_change_](https://github.com/dbt-labs/dbt-adapters/blob/313d4a506984b5c024d51a110eb9beaeef58fcfa/dbt/include/global_project/macros/materializations/models/incremental/on_schema_change.sql#L102) after creating the temp relation and before merging. Similar to dbt-spark's [incremental materialization](https://github.com/dbt-labs/dbt-spark/blob/212442322b509eb34deee2ac000c85c1e4daba73/dbt/include/spark/macros/materializations/incremental/incremental.sql#L58).
It will allow the "ignore", "fail" and "append\_new\_columns" as _on\_schema\_change_ strategy but not the "sync\_all\_columns" because the macro [spark\_\_alter\_relation\_add\_remove\_columns](https://github.com/dbt-labs/dbt-spark/blob/212442322b509eb34deee2ac000c85c1e4daba73/dbt …
=> Add on_schema_change possibility

CHANGELOG.md, dbt/adapters/glue/column.py, tests/unit/test_column.py
resolves #423 
I changed the parent class of GlueColumn from Column (from dbt base) to SparkColumn
=> Changed GlueColumn base class

CHANGELOG.md, dbt/adapters/glue/impl.py
resolves #421 
Modify the function [get_columns_in_relation](https://github.com/aws-samples/dbt-glue/blob/726ae4c79a88a75c2e600ab54151998997707bc4/dbt/adapters/glue/impl.py#L206) so it does not return unwanted partitions related stuff like "Part 0", "Part 1", ... For more information on this behavior see [421](https://github.com/aws-samples/dbt-glue/issues/421)
FYI : There are currently a "fake" tests associated with this function. I can update it to add one but I need information on how to mock a _BaseRelation_ object. 
=> Strip unwanted partition columns

CHANGELOG.md, dbt/adapters/glue/gluedbapi/cursor.py
resolves #433 
Modified the DbtDatabaseError from dbt to dbt_common
FYI : I am not sure wether this change needs testing, if it does, I would be interested in understanding how to!
Same as in the #433 issue but then got the following output : 
```bash
09:19:04  Running with dbt=1.8.4
09:19:05  Registered adapter: glue=1.8.1
09:19:05  Found 41 models, 2 snapshots, 1 seed, 2 operations, 1 test, 1 source, 1367 macros
09:19:05  
09:19:07  
09:19:07  
09:19:07  1 of 1 START sql incremental model xxx.test_database_error ............ [RUN]
09:19:17  Glue adapter: Glue returned `error` for statement None for code 
spark.sql("""
select "a" as id …
```
=> Fix unraised DbtDatabaseError

CHANGELOG.md, dbt/adapters/glue/gluedbapi/connection.py
resolves [#439](https://github.com/aws-samples/dbt-glue/issues/439)
Add exceptions import:
`
from dbt.adapters.exceptions.connection import FailedToConnectError
from dbt_common.exceptions import ExecutableError
`
=> fix: add correct import for exceptions

CHANGELOG.md, dbt/adapters/glue/impl.py, dbt/include/glue/macros/materializations/incremental/incremental.sql
resolves part of #415 
Add write option for creating table with file format Delta when using incremental strategy. For example, it allows --full-refresh when changing schema by adding a config : _delta_create_table_write_options = {"mergeSchema": "true"}_ to your model.
Credits : Nicolas Fourmann initially found this solution ! 
FYI : I am not sure wether this change needs testing, if it does, I would be interested in understanding how to! 
Simple model with minimal incremental merge strategy : 
```sql
{{
config(
materialized='incremental',
incremental_strategy='merge',
unique_key=['id'],
file_format='delta',
)
}}
with incoming_data as (
select 1 …
```
=> Adding minimal write option when creating table with Delta format

CHANGELOG.md, dbt/adapters/glue/impl.py
resolves #430 
To reproduce the bug create a seed file `myseed.csv' with the following content : 
```
adapter,version
glue,1.8.1
spanner,
```
Launch `dbt seed` and you'll get this output 
```
❯ dbt seed
16:35:37  Running with dbt=1.8.6
16:35:37  Registered adapter: glue=1.8.1
16:35:38  Found 1 seed, 879 macros
16:35:38
16:35:38  Concurrency: 1 threads (target='dev-glue')
16:35:38
16:35:38  1 of 1 START seed file dbt.myseed .............................................. [RUN]
16:36:38  Glue adapter: Glue returned `error` for statement None for code
csv = [{"adapter": "glue", "version": "1.8.1"}, {"adapter": "spanner", "version": null}]
df = spark.createDataFrame(csv)
table_name = 'dbt.myseed'
if (spark.sql("show tables in dbt").where("tableName == 'myseed'").count() > 0):
df.write …
```
=> Fix null values handling in seeds

CHANGELOG.md, dbt/adapters/glue/impl.py
resolves #429 
To reproduce the Bug create a seed file named `MySeed.csv ` in your seed folder with the following content : 
```
adapter,version
glue,1.8.1
```
Run 2 times : `dbt seed`
The first time the table did not exist in glue metastore, so the command pass.
```
❯ dbt seed
14:37:32  Running with dbt=1.8.6
14:37:33  Registered adapter: glue=1.8.1
14:37:33  Found 1 seed, 879 macros
14:37:33
14:37:34  Concurrency: 1 threads (target='dev-glue')
14:37:34
14:37:34  1 of 1 START seed file dbt.MySeed .............................................. [RUN]
14:37:51  1 of 1 OK loaded seed file dbt.MySeed .......................................... [CREATE 1 in 16.85s]
14:37:51
14:37:51  Finished running 1 seed in 0 hours 0 minutes and 17.59 seconds (17.59s).
14:37:51
14:37:51  Completed …
```
=> Fix the case-sensitive comparison on the seed name

CHANGELOG.md, dbt/adapters/glue/impl.py, tests/unit/test_adapter.py
resolves #446 
This pull requests allows to upload seeds with serialized lengths over 68000 characters. It allows so by splitting csv records across chunks which are appended to a session variable on different statement executions.
=> Allow big seeds

CHANGELOG.md, dbt/adapters/glue/credentials.py, tests/unit/test_credentials.py
Upgrade default Glue version to 5.0
=> Upgrade default Glue version to 5.0

CHANGELOG.md, dbt/adapters/glue/impl.py, tests/unit/test_adapter.py
resolves #516
The method ```list_relations_without_caching``` is returning ```None``` when trying to list relations from a non existing database, this causes a failure on the base adapter when computing the schema cache. 
This pr captures the ```EntityNotFoundException``` exception to return an empty list for such cases. This behaviour is consistent with other adapter implementations, such as dbt-spark where ```Database '<database name>' not found``` is captured to return empty array.
=> fix list_relations_without_caching for missing database

CHANGELOG.md, dbt/adapters/glue/impl.py
resolves #503
The error occurs when DESCRIBE statement is triggered.
The fix is to change the table identifier for tmp table created for incremental model.
Currently, the temp table for incremental has suffix of `_tmp`, and the temp table for snapshot has suffix of `_dbt_tmp`
The fix is only for the former. 
=> Fix the get_columns_in_relation function error when on_schema_change is specified

dbt/adapters/glue/gluedbapi/connection.py, tests/unit/gluedbapi/test_connection.py
resolves #513
I was having some issues related to the mentioned issue when developing some other changes on the adapter, fixed the error I was getting plus refactored to match codebase standard. 
New test was added on GlueConnection for affected use case.
CHANGELOG remains unchanged since change affects unreleased funcionality.
=> fix 'botocore' not is not defined and add test on GlueConnection.state

dbt/include/glue/macros/iceberg_helper.sql, tests/functional/adapter/test_iceberg.py
Fast follow fix for https://github.com/aws-samples/dbt-glue/pull/525
* Changed to keep update_iceberg_ts column fresh
=> Changed to keep update_iceberg_ts column fresh

CHANGELOG.md, dbt/include/glue/macros/materializations/snapshot.sql
This PR adds refresh table when missing columns are detected
=> Add refresh table when missing columns are detected

CHANGELOG.md, dbt/include/glue/macros/adapters.sql
This PR fixes the issue 2 described here: https://github.com/aws-samples/dbt-glue/issues/486
The macro `spark__alter_relation_add_remove_columns` is implemented in dbt-spark and it calls run_query method. However, in dbt-glue, `run_query` method expects results including metadata, alter table always fails because of this.
To avoid that, we overwrite `spark__alter_relation_add_remove_columns`  in adapters.sql.
=> Fix ALTER TABLE ADD COLUMN returning None

CHANGELOG.md, README.md, dbt/adapters/glue/credentials.py, dbt/adapters/glue/gluedbapi/connection.py, dbt/include/glue/macros/adapters.sql, dbt/include/glue/macros/materializations/incremental/incremental.sql, tests/functional/conftest.py, tests/unit/macros/test_macros.py
resolves #569
I added the ability for one to specify a different schema for temporary tables to be created in so that they can be physically isolated under different management and lifecycle rules and security policies than the target Glue database within the same Glue catalog.  For example, if you have a database in Lake Formation in a different AWS account that is cataloged in your local Glue catalog through a resource link, and this is where your target data assets are managed, but you don't want to muddy that database with temporary tables that may have restrictions through Lake Formation, you can specify a different schema/database in the same catalog that would not be the resource link.  This way as well, if data files are not cleaned up appropriately, they can be easily managed …
=> Temp schema

CHANGELOG.md, dbt/include/glue/macros/materializations/incremental/incremental.sql, dbt/include/glue/macros/materializations/incremental/strategies.sql, tests/functional/adapter/test_iceberg.py
Fixes issue where incremental_strategy='merge' + on_schema_change='append_new_columns' was incorrectly using INSERT INTO instead of MERGE INTO for Iceberg tables.
resolves #571
- Fix incremental.sql to use proper strategy instead of hardcoded INSERT when schema changes occur
- Update get_merge_sql to handle explicit column lists for schema changes
- Add dest_columns parameter to dbt_glue_get_incremental_sql
- Add test case for merge + schema change combination to prevent regression
=> Fix merge strategy with schema changes for Iceberg tables
